version: '3.9'

services:
  web:
    build: .
    container_name: healthcare_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/healthcare_db
    restart: always

  db:
    image: postgres:15
    container_name: healthcare_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare_db
    volumes:
      - healthcare_data:/var/lib/postgresql/data

volumes:
  healthcare_data:
